version: "3.9"  # новіша версія без deprecated warnings
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /app
    env_file: .env
    restart: always
    ports:
      - "3000:3000"
    # обмеження ресурсів
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    volumes:
      - .:/app
    entrypoint: /entrypoint.sh

  studio_pangeya_nginx:
    image: nginx:1.19
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
