version: "3.7"
services:
  app:
    working_dir: /app
    env_file: .env
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/app
    entrypoint: /entrypoint.sh
    ports:
      - "3000:3000"
  studio_pangeya_nginx:
    image: nginx:1.19
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
